-- liquibase formatted sql

-- changeset ?:1644278789681-1
CREATE TABLE "public"."person" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "firstname" TEXT, "lastname" TEXT, "addressid" BIGINT, "pruebaxxx" VARCHAR, CONSTRAINT "pk_person_id" PRIMARY KEY ("id"));

-- changeset ?:1644278789681-2
CREATE SEQUENCE  IF NOT EXISTS "public"."person_pk_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 CACHE 1;

-- changeset ?:1644278789681-3
CREATE TABLE "public"."login" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "personid" BIGINT NOT NULL, "email" TEXT, "password" TEXT NOT NULL, "pin" TEXT, CONSTRAINT "pk_login_id" PRIMARY KEY ("id"));

-- changeset ?:1644278789681-4
CREATE SEQUENCE  IF NOT EXISTS "public"."login_pk_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 CACHE 1;

-- changeset ?:1644278789681-5
CREATE TABLE "public"."address" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "street" TEXT, "city" TEXT, "state" TEXT, "postalcode" TEXT, "countrycode" TEXT, "latitude" numeric(0), "longitude" numeric(0), CONSTRAINT "pk_address_id" PRIMARY KEY ("id"));

-- changeset ?:1644278789681-6
CREATE SEQUENCE  IF NOT EXISTS "public"."address_pk_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 0 MAXVALUE 2147483647 CACHE 1;

-- changeset ?:1644278789681-7
ALTER TABLE "public"."login" ADD CONSTRAINT "id" UNIQUE ("personid");

-- changeset ?:1644278789681-8
ALTER TABLE "public"."person" ADD CONSTRAINT "address_fk" FOREIGN KEY ("addressid") REFERENCES "stealthis"."address" ("id") ON UPDATE CASCADE ON DELETE CASCADE;

-- changeset ?:1644278789681-9
ALTER TABLE "public"."login" ADD CONSTRAINT "person_fk" FOREIGN KEY ("personid") REFERENCES "stealthis"."person" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset ?:1644278789681-10
ALTER TABLE "public"."person" ADD CONSTRAINT "id_address_person" UNIQUE ("addressid");

-- changeset ?:1644278789681-11
ALTER TABLE "public"."login" ADD CONSTRAINT "unique_email" UNIQUE ("email");

-- changeset ?:1644278789681-12
CREATE TABLE "public"."example" ("id" VARCHAR);

